# -*- coding: utf-8 -*-
"""C7 project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YD2ymOg5mxnmzq29IXhHJsN3j_32f7PU

士兵
"""

position1= input().split()
position2= input().split()
x1,y1= int(position1[0]),int(position1[1])
x2,y2= int(position2[0]), int(position2[1])
if (x2==x1 and y2==y1) or checkerboard[x2][y2]==1:
  print("No")
elif x2==x1+1 and y2==y1:
  print("Yes")
else:
  print("No")

"""騎士"""

position1= input().split()
position2= input().split()
x1,y1= int(position1[0]),int(position1[1])
x2,y2= int(position2[0]), int(position2[1])
if (abs(x2-x1)==1 and abs(y2-y1)==2) or (abs(x2-x1)==2 and abs(y2-y1)==1):
  print("Yes")
elif (x2==x1 and y2==y1) or checkerboard[x2][y2]==1:
  print("No")
else:
  print("No")

"""國王"""

position1= input().split()
position2= input().split()
x1,y1= int(position1[0]),int(position1[1])
x2,y2= int(position2[0]), int(position2[1])
if (x2==x1 and y2==y1) or checkerboard[x2][y2]==1:
  print("No")
elif abs(x2-x1)<=1 and abs(y2-y1)<=1:
  print("Yes")
else:
  print("No")

"""皇后"""

position1= input().split()
position2= input().split()
x1,y1= int(position1[0]), int(position1[1])
x2,y2= int(position2[0]), int(position2[1])
if checkerboard[x2][y2]==1:
   print("No")
elif (x2==x1 and y2==y1) or (abs(x2-x1)!= abs(y2-y1) and x1!=x2 and y1!=y2):
   print("No")
else:
  dx=(x2-x1)//max(1, abs(x2-x1))
  dy=(y2-y1)//max(1, abs(y2-y1))
  cx,cy=x1+dx,y1+dy
  reachable=True
  while cx!=x2 or cy!=y2:
    if checkerboard[cx][cy]==1:
      reachable=False
      break
    cx=cx+dx
    cy=cy+dy
  if reachable:
    print("Yes")
  else:
    print("No")